export const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES'
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS'
export const FETCH_ALL_RECIPES_FAILED = 'FETCH_ALL_RECIPES_FAILED'

export const FETCH_RECIPE = 'FETCH_RECIPE'
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS'
export const FETCH_RECIPE_FAILED = 'FETCH_RECIPE_FAILED'

export const ADD_RECIPE = 'ADD_RECIPE'
export const ADD_RECIPE_FAILED = 'ADD_RECIPE_FAILED'
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS'

export const UPDATE_RECIPE = 'UPDATE_RECIPE'
export const UPDATE_RECIPE_FAILED = 'UPDATE_RECIPE_FAILED'
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS'

export const DELETE_RECIPE = 'DELETE_RECIPE'
export const DELETE_RECIPE_FAILED = 'ADD_RECIPE_FAILED'
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS'

export const SET_ACTIVE_RECIPE = 'SET_ACTIVE_RECIPE'
export const ADD_RATING = 'ADD_RATING'
export const ADD_RATING_SUCCESS = 'ADD_RATING_SUCCESS'